Feature validation
AsahiSasaki/taskmanager-front pull request #2
Opened 2024-02-21 05:28 UTC by AsahiSasaki

バリデーションの実装と、構成整理をしました。

2024-02-24 08:37 UTC, shota-ootani-excite requested changes

2024-02-24 08:37 UTC, shota-ootani-excite commented on src/pages/TaskManager.tsx
> +                <TaskDialog
問題はないのですが、TaskDialogはBoxの外でも良いのではと思いました。

2024-02-24 08:37 UTC, shota-ootani-excite commented on src/pages/TaskManager.tsx
> +                    selectedId={selectedId ? selectedId : null}
selectedIdをそのまま渡せるような実装にすると見栄えがいいと思います。

2024-02-24 08:37 UTC, shota-ootani-excite commented on src/models/TaskData.ts
> +export type TaskData = z.infer<typeof TaskDataSchema>
idやstatusはユーザーが入力しないので、validationのschemaとmodel定義は別で考えたほうが良いかと思いました。

2024-02-24 08:37 UTC, shota-ootani-excite commented on src/hooks/UseTaskList.tsx
> +export default useTaskList
5行目でexportしているので不要かと思います。

2024-02-24 08:37 UTC, shota-ootani-excite commented on src/components/TaskDialog.tsx
> +    } = useTaskForm(Number(selectedId), handleClose, open)
useTaskFormとTaskDialogでselectedIdの定義を同じにして良いと思いますがどうでしょう？
Number()も不要かと思います。

2024-02-26 06:51 UTC, hikaru-onishi requested changes

2024-02-26 06:51 UTC, hikaru-onishi commented on src/hooks/UseTaskForm.ts
ファイル名はHooks名とあわせて小文字始まりでいいと思います。
命名規則は以下を参考にしてください。（Reactコンポーネント以外はファイル名も小文字始まりでいいと思います）
https://ja.react.dev/learn/reusing-logic-with-custom-hooks#hook-names-always-start-with-use

2024-02-26 06:51 UTC, hikaru-onishi commented on src/models/TaskData.ts
> +}
/models内に定義する内容ではないように感じました。
汎用的なロジックとして別で切り出した方がいいと思います。

2024-02-26 08:01 UTC, AsahiSasaki commented on src/pages/TaskManager.tsx
> +                <TaskDialog
指摘の通り、TaskDialogをBoxの外に出しました。

2024-02-26 08:02 UTC, AsahiSasaki commented on src/pages/TaskManager.tsx
> +                    selectedId={selectedId ? selectedId : null}
selectedId={selectedId}
と渡すように修正しました。

2024-02-26 08:06 UTC, AsahiSasaki commented on src/models/TaskData.ts
> +export type TaskData = z.infer<typeof TaskDataSchema>
SchemaとModelを分けて定義しました。
statusは更新時に状態を変えるので、Schemaにも定義しています。

2024-02-26 08:07 UTC, AsahiSasaki commented on src/hooks/UseTaskList.tsx
> +export default useTaskList
default exportしている箇所をnamed exportに修正しました。

2024-02-26 08:07 UTC, AsahiSasaki commented on src/components/TaskDialog.tsx
> +    } = useTaskForm(Number(selectedId), handleClose, open)
指摘通り対応しました。

2024-02-26 08:08 UTC, AsahiSasaki commented on src/hooks/UseTaskForm.ts
指摘通り対応しました。

2024-02-26 08:11 UTC, AsahiSasaki commented on src/models/TaskData.ts
> +}
src/utils/validationUtils
に定義しました。

2024-02-27 05:33 UTC, hikaru-onishi commented on src/hooks/UseTaskForm.ts
ファイル名の変更が反映されていないようです。
ファイル名の大文字小文字は、Gitのデフォルト設定では差分として認識されないので、適当な名前でコミットしてから再度名前を変更するか、Gitの設定を変更する必要があります。

2024-02-27 05:58 UTC, AsahiSasaki commented on src/hooks/UseTaskForm.ts
Gitの設定変更しました。

2024-02-27 06:27 UTC, hikaru-onishi approved these changes

2024-02-27 07:17 UTC, shota-ootani-excite approved these changes

2024-02-29 04:34 UTC, merged